import Head from 'next/head'
import { serialize } from 'next-mdx-remote/serialize'
import { MDXRemote, MDXRemoteSerializeResult } from 'next-mdx-remote'
import { getProjects } from '@lib/api'

const Test = () => <span>TEST COMPO</span>

const components = { Test }

type Props = {
  projects: MDXRemoteSerializeResult[]
}

const Home = ({ projects }: Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        LESTON
        <div>
          {projects.map((project, idx) => (
            <MDXRemote
              key={'project' + idx}
              {...project}
              components={components}
            />
          ))}
        </div>
      </div>
    </div>
  )
}

export default Home

export async function getStaticProps() {
  const projectsData = getProjects(['content'])

  const projects = await Promise.all(
    projectsData.map(
      async ({ content, data }) => await serialize(content, { scope: data })
    )
  )

  return { props: { projects } }
}
